"""Indexes and uniqueness

Revision ID: 2bc4a22bab4b
Revises: e706a1f3d6e2
Create Date: 2026-04-04 17:10:11.067744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc4a22bab4b'
down_revision: Union[str, Sequence[str], None] = 'e706a1f3d6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_outbox_handled_at', 'outbox', ['handled_at'], unique=False)
    op.create_index('ix_outbox_status', 'outbox', ['status'], unique=False)
    op.create_index('ix_outbox_status_handled_at', 'outbox', ['status', 'handled_at'], unique=False)
    op.drop_constraint(op.f('uq_payment_idempotency'), 'payments', type_='unique')
    op.create_index('ix_payments_idempotency_key', 'payments', ['idempotency_key'], unique=False)
    op.create_index('ix_payments_payment_id', 'payments', ['id'], unique=False)
    op.create_unique_constraint('uq_payments_id', 'payments', ['id'])
    op.create_unique_constraint('uq_payments_idempotency_key', 'payments', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payments_idempotency_key', 'payments', type_='unique')
    op.drop_constraint('uq_payments_id', 'payments', type_='unique')
    op.drop_index('ix_payments_payment_id', table_name='payments')
    op.drop_index('ix_payments_idempotency_key', table_name='payments')
    op.create_unique_constraint(op.f('uq_payment_idempotency'), 'payments', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_outbox_status_handled_at', table_name='outbox')
    op.drop_index('ix_outbox_status', table_name='outbox')
    op.drop_index('ix_outbox_handled_at', table_name='outbox')
    # ### end Alembic commands ###
