"""Update schema

Revision ID: e706a1f3d6e2
Revises: 7ef11ac9027d
Create Date: 2026-04-02 18:29:06.200763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e706a1f3d6e2'
down_revision: Union[str, Sequence[str], None] = '7ef11ac9027d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'outbox', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outbox', type_='unique')
    # ### end Alembic commands ###
